apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deploy
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.spec.replicas }}
  strategy:
    type: {{ .Values.spec.type }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: sample-container
          image: {{ .Values.image.image }}
          ports:
            - containerPort: {{ .Values.image.port }}
          imagePullPolicy: {{ .Values.image.pullpolicy }}
          restartPolicy: {{ .Values.image.restartpolicy }}
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}
  ports:
    - name: nginx-port
      port: 80
      targetPort: {{ .Values.image.port }}
      protocol: TCP
      nodePort: {{ .Values.service.nodeport }}
